// _variables.tf

variable "subscription_id" {
  description = "Azure Subscription Id for the bootstrap resources. Leave empty to use the az login subscription"
  type        = string
  default     = ""

  validation {
    condition = (
      var.subscription_id == ""
      || can(regex(
        "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$",
        var.subscription_id,
      ))
    )
    error_message = "Azure subscription id must be a valid GUID"
  }
}

variable "enable_extended_resource_providers" {
  description = "Enable extended resource providers registration"
  type        = bool
  default     = true
}

variable "enable_all_resource_providers" {
  description = "Enable alll resource providers registration"
  type        = bool
  default     = false
}

// tflint-ignore: terraform_unused_declarations
variable "default_registered_resource_providers" {
  description = "List of registered Azure resource providers by default."
  type        = list(string)
  default = [
    "Microsoft.ADHybridHealthService",
    "Microsoft.Authorization",
    "Microsoft.Billing",
    "Microsoft.ClassicSubscription",
    "Microsoft.Commerce",
    "Microsoft.Consumption",
    "Microsoft.CostManagement",
    "Microsoft.Features",
    "Microsoft.MarketplaceOrdering",
    "Microsoft.Portal",
    "Microsoft.ResourceGraph",
    "Microsoft.ResourceNotifications",
    "Microsoft.Resources",
    "Microsoft.SerialConsole",
    "Microsoft.support",
  ]
}

variable "required_resource_providers" {
  description = "List of required Azure resource providers to register."
  type        = list(string)
  default = [
    "Microsoft.Advisor",
    "Microsoft.Compute",
    "Microsoft.Diagnostics",
    "Microsoft.KeyVault",
    "Microsoft.ManagedIdentity",
    "Microsoft.Network",
    "Microsoft.PolicyInsights",
    "Microsoft.Security",
    "Microsoft.SecurityInsights",
    "Microsoft.Storage",
  ]
}

variable "extended_required_resource_providers" {
  description = "List of required Azure resource providers to register."
  type        = list(string)
  default = [
    "Github.Network",
    "Microsoft.AVS",
    "Microsoft.AlertsManagement",
    "Microsoft.ApiManagement",
    "Microsoft.App",
    "Microsoft.AppConfiguration",
    "Microsoft.AppPlatform",
    "Microsoft.Automation",
    "Microsoft.Blueprint",
    "Microsoft.BotService",
    "Microsoft.Cache",
    "Microsoft.Cdn",
    "Microsoft.CognitiveServices",
    "Microsoft.ContainerInstance",
    "Microsoft.ContainerRegistry",
    "Microsoft.ContainerService",
    "Microsoft.CustomProviders",
    "Microsoft.DBforMariaDB",
    "Microsoft.DBforMySQL",
    "Microsoft.DBforPostgreSQL",
    "Microsoft.Dashboard",
    "Microsoft.DataFactory",
    "Microsoft.DataLakeAnalytics",
    "Microsoft.DataLakeStore",
    "Microsoft.DataMigration",
    "Microsoft.DataProtection",
    "Microsoft.Databricks",
    "Microsoft.DesktopVirtualization",
    "Microsoft.DevTestLab",
    "Microsoft.Devices",
    "Microsoft.DocumentDB",
    "Microsoft.EventGrid",
    "Microsoft.EventHub",
    "Microsoft.GuestConfiguration",
    "Microsoft.HealthcareApis",
    "Microsoft.HDInsight",
    "Microsoft.IoTCentral",
    "Microsoft.Kusto",
    "Microsoft.Logic",
    "Microsoft.MachineLearningServices",
    "Microsoft.Maintenance",
    "Microsoft.ManagedServices",
    "Microsoft.Management",
    "Microsoft.Maps",
    "Microsoft.MixedReality",
    "Microsoft.Monitor",
    "Microsoft.NotificationHubs",
    "Microsoft.OperationalInsights",
    "Microsoft.OperationsManagement",
    "Microsoft.PowerBIDedicated",
    "Microsoft.RecoveryServices",
    "Microsoft.Relay",
    "Microsoft.Search",
    "Microsoft.ServiceBus",
    "Microsoft.ServiceFabric",
    "Microsoft.SignalRService",
    "Microsoft.Sql",
    "Microsoft.StreamAnalytics",
    "Microsoft.Web",
    "microsoft.insights",
  ]
}

variable "all_resource_providers" {
  description = "List of required Azure resource providers to register."
  type        = list(string)
  default = [
    "Microsoft.AAD",
    "Microsoft.AadCustomSecurityAttributesDiagnosticSettings",
    "Microsoft.aadiam",
    "Microsoft.Addons",
    "Microsoft.AgFoodPlatform",
    "Microsoft.AgriculturePlatform",
    "Microsoft.AnalysisServices",
    "Microsoft.ApiCenter",
    "Microsoft.AppAssessment",
    "Microsoft.AppComplianceAutomation",
    "Microsoft.AppConfiguration",
    "Microsoft.ApplicationMigration",
    "Microsoft.Attestation",
    "Microsoft.Automanage",
    "Microsoft.AwsConnector",
    "Microsoft.AzureActiveDirectory",
    "Microsoft.AzureArcData",
    "Microsoft.AzureBusinessContinuity",
    "Microsoft.AzureDataTransfer",
    "Microsoft.AzureFleet",
    "Microsoft.AzureImageTestingForLinux",
    "Microsoft.AzureLargeInstance",
    "Microsoft.AzurePlaywrightService",
    "Microsoft.AzureScan",
    "Microsoft.AzureSphere",
    "Microsoft.AzureStack",
    "Microsoft.AzureStackHCI",
    "Microsoft.AzureTerraform",
    "Microsoft.BackupSolutions",
    "Microsoft.BareMetal",
    "Microsoft.BareMetalInfrastructure",
    "Microsoft.Batch",
    "Microsoft.BillingBenefits",
    "Microsoft.Bing",
    "Microsoft.BlockchainTokens",
    "Microsoft.Capacity",
    "Microsoft.Carbon",
    "Microsoft.CertificateRegistration",
    "Microsoft.ChangeAnalysis",
    "Microsoft.Chaos",
    "Microsoft.ClassicCompute",
    "Microsoft.ClassicInfrastructureMigrate",
    "Microsoft.ClassicNetwork",
    "Microsoft.ClassicStorage",
    "Microsoft.CleanRoom",
    "Microsoft.CloudDevicePlatform",
    "Microsoft.CloudHealth",
    "Microsoft.CloudShell",
    "Microsoft.CloudTest",
    "Microsoft.CodeSigning",
    "Microsoft.Communication",
    "Microsoft.Community",
    "Microsoft.Compute",
    "Microsoft.ComputeSchedule",
    "Microsoft.ConfidentialLedger",
    "Microsoft.Confluent",
    "Microsoft.ConnectedCache",
    "Microsoft.ConnectedCredentials",
    "Microsoft.connectedopenstack",
    "Microsoft.ConnectedVehicle",
    "Microsoft.ConnectedVMwarevSphere",
    "Microsoft.CostManagementExports",
    "Microsoft.CustomerLockbox",
    "Microsoft.D365CustomerInsights",
    "Microsoft.DatabaseFleetManager",
    "Microsoft.DatabaseWatcher",
    "Microsoft.DataBox",
    "Microsoft.DataBoxEdge",
    "Microsoft.Datadog",
    "Microsoft.DataReplication",
    "Microsoft.DataShare",
    "Microsoft.DependencyMap",
    "Microsoft.DevCenter",
    "Microsoft.DevelopmentWindows365",
    "Microsoft.DevHub",
    "Microsoft.DeviceOnboarding",
    "Microsoft.DeviceRegistry",
    "Microsoft.DeviceUpdate",
    "Microsoft.DevOpsInfrastructure",
    "Microsoft.DigitalTwins",
    "Microsoft.Discovery",
    "Microsoft.DomainRegistration",
    "Microsoft.DurableTask",
    "Microsoft.Easm",
    "Microsoft.Edge",
    "Microsoft.EdgeManagement",
    "Microsoft.EdgeMarketplace",
    "Microsoft.EdgeOrder",
    "Microsoft.EdgeOrderPartner",
    "Microsoft.EdgeZones",
    "Microsoft.Elastic",
    "Microsoft.ElasticSan",
    "Microsoft.EnterpriseSupport",
    "Microsoft.EntitlementManagement",
    "Microsoft.EntraIDGovernance",
    "Microsoft.Experimentation",
    "Microsoft.ExtendedLocation",
    "Microsoft.Fabric",
    "Microsoft.Falcon",
    "Microsoft.Features",
    "Microsoft.FluidRelay",
    "Microsoft.GraphServices",
    "Microsoft.HanaOnAzure",
    "Microsoft.HardwareSecurityModules",
    "Microsoft.HealthBot",
    "Microsoft.HealthcareInterop",
    "Microsoft.HealthDataAIServices",
    "Microsoft.HealthModel",
    "Microsoft.HealthPlatform",
    "Microsoft.Help",
    "Microsoft.HybridCloud",
    "Microsoft.HybridCompute",
    "Microsoft.HybridConnectivity",
    "Microsoft.HybridContainerService",
    "Microsoft.HybridNetwork",
    "Microsoft.Impact",
    "Microsoft.IntegrationSpaces",
    "Microsoft.IoTFirmwareDefense",
    "Microsoft.IoTOperations",
    "Microsoft.IoTOperationsDataProcessor",
    "Microsoft.IoTSecurity",
    "Microsoft.KeyVault",
    "Microsoft.Kubernetes",
    "Microsoft.KubernetesConfiguration",
    "Microsoft.KubernetesRuntime",
    "Microsoft.LabServices",
    "Microsoft.LoadTestService",
    "Microsoft.ManagedNetworkFabric",
    "Microsoft.ManufacturingPlatform",
    "Microsoft.Marketplace",
    "Microsoft.MarketplaceNotifications",
    "Microsoft.MessagingCatalog",
    "Microsoft.MessagingConnectors",
    "Microsoft.Migrate",
    "Microsoft.Mission",
    "Microsoft.MobileNetwork",
    "Microsoft.MySQLDiscovery",
    "Microsoft.NetApp",
    "Microsoft.NetworkCloud",
    "Microsoft.NetworkFunction",
    "Microsoft.NexusIdentity",
    "Microsoft.Nutanix",
    "Microsoft.ObjectStore",
    "Microsoft.OffAzure",
    "Microsoft.OffAzureSpringBoot",
    "Microsoft.OnlineExperimentation",
    "Microsoft.OpenEnergyPlatform",
    "Microsoft.OperatorVoicemail",
    "Microsoft.OracleDiscovery",
    "Microsoft.Orbital",
    "Microsoft.PartnerManagedConsumerRecurrence",
    "Microsoft.Peering",
    "Microsoft.Pki",
    "Microsoft.PowerBI",
    "Microsoft.PowerPlatform",
    "Microsoft.Premonition",
    "Microsoft.ProfessionalService",
    "Microsoft.ProgrammableConnectivity",
    "Microsoft.ProviderHub",
    "Microsoft.Purview",
    "Microsoft.Quantum",
    "Microsoft.Quota",
    "Microsoft.RecommendationsService",
    "Microsoft.RedHatOpenShift",
    "Microsoft.Relationships",
    "Microsoft.ResourceConnector",
    "Microsoft.ResourceHealth",
    "Microsoft.SaaS",
    "Microsoft.SaaSHub",
    "Microsoft.Scom",
    "Microsoft.SCVMM",
    "Microsoft.SecretSyncController",
    "Microsoft.SecurityCopilot",
    "Microsoft.SecurityDetonation",
    "Microsoft.SecurityPlatform",
    "Microsoft.SentinelPlatformServices",
    "Microsoft.ServiceFabricMesh",
    "Microsoft.ServiceLinker",
    "Microsoft.ServiceNetworking",
    "Microsoft.ServicesHub",
    "Microsoft.Singularity",
    "Microsoft.SoftwarePlan",
    "Microsoft.Solutions",
    "Microsoft.Sovereign",
    "Microsoft.SqlVirtualMachine",
    "Microsoft.StandbyPool",
    "Microsoft.StorageActions",
    "Microsoft.StorageCache",
    "Microsoft.StorageMover",
    "Microsoft.StorageSync",
    "Microsoft.StorageTasks",
    "Microsoft.StreamAnalytics",
    "Microsoft.Subscription",
    "Microsoft.SustainabilityServices",
    "Microsoft.Synapse",
    "Microsoft.Syntex",
    "Microsoft.ToolchainOrchestrator",
    "Microsoft.UpdateManager",
    "Microsoft.UsageBilling",
    "Microsoft.VerifiedId",
    "Microsoft.VideoIndexer",
    "Microsoft.VirtualMachineImages",
    "Microsoft.visualstudio",
    "Microsoft.VMware",
    "Microsoft.VoiceServices",
    "Microsoft.WeightsAndBiases",
    "Microsoft.Windows365",
    "Microsoft.WindowsPushNotificationServices",
    "Microsoft.WorkloadBuilder",
    "Microsoft.Workloads",
  ]
}
